### ISSUE TITLE
Unable to start machine

### ISSUE THREAD

**Issue by syn-ack-zack** [brianwarehime/goldphish#2]
On Windows using Python 2.7 I specify python path and the working directory with the .mtz and *.py files in the machine config. When I try to run the machine within Maltego I am thrown this error.

**The machine target(s) could not be created. Please make sure that you have discovered or imported the required entity types or if no specific entity types are required please run the machine on selected entities.**

The Machine config is not showing any input for Goldphish  [ ]

![goldphish](https://cloud.githubusercontent.com/assets/2582445/11369461/08a69e74-928d-11e5-9fd0-6375a4b455b8.PNG)

I am rather new to Maltego, so I may be missing another way to feed the domain in.

**Comment by ihaveaq** [comment]
Did you find an answer to this? I am having the same issue.

**Comment by syn-ack-zack** [comment]
If I recall correctly I had not first selected the maltego.Domain entity. Make sure you have the Paterva CTAS transform set, as that will give you access to the Domain entity. Place a domain on a new graph and fill in whatever domain you want to run the transform on. When you select/highlight the domain it should indicate applicable machines to run in the bottom left menu. Running the machine while the entity is selected should have it yield the correct results.
